### PR TITLE
Futures strategies

### PR DESCRIPTION
**Pull request by caglarylmz**
## Summary

Convert and add some strategies for binance futures

### CODE REVIEW

**Review by xmatthias — APPROVED** [review]
I'm sure the strategies work, but i'm not sure if they're really profitable.
usually "simple" reversion of signals is not the best way for this.

Yet - these can serve well as examples on how to write futures strategies.

**Comment by caglarylmz** [comment]
My purpose here is not profitability, but to present different examples of future trading. I would also like to see different strategies for profitability. If i catch a strategy i will definitely post it :)
thx..

**Comment by caglarylmz** [comment]
> I am getting the followin error for all the strategies in 'futures'
> 
> ERROR - Impossible to load Strategy 'f_adx_sma_strategy.py'. This class does not exist or contains Python code errors
> 
> Non-Future strategies are working fine.
> 
> Please advice. Thanks

Pls read readme.md and use config file. this strategy works backtest, hyperopts, dry-run and live.

**Comment by caglarylmz** [comment]
> 

Pls read readme.md and use config file. this strategy works backtest, hyperopts, dry-run and live.

**Pull request merged**
