### PR TITLE
hyperopt for AverageStrategy.py

### PR DESCRIPTION
**Pull request by OtenMoten**
Hello dear community, 

I'm totally agree with @hroff-1902 in #33 that every strategy from [the freqtrade-strategies repository](https://github.com/freqtrade/freqtrade-strategies/tree/master/user_data/strategies/berlinguyinca) written by @berlinguyinca should have a proper hyper-optimization to gain the optimal parameters for the strategy.

Therefore, I wrote the the hyper-optimization for `AverageStrategy.py`. Feel free to contribute.

You can find the file also in [my own repository (click here)](https://github.com/OtenMoten/Dobby-Trading-Elf/blob/master/freqtrade/freqtrade/optimize/EMACrossOpt.py). Don't wonder, I renamed the name of the strategy on my side. `EMACross.py` means `AverageStrategy.py`, therefore I also named the hyper-optimization file `EMACrossOpt.py` instead of `AverageStrategyOpt.py`. <br>
Ask if anything isn't working or unclear.

Kind regards
Kevin

## The Code
```
__author__ = "Kevin Ossenbrueck"
__creator__ = "Kevin Ossenbrueck"
__copyright__ = "Free for all"
__credits__ = ["MontrealTradingGroup", "Udemy", "Mohsen Hassan", "Ilyass Tabiai"]
__license__ = "GNU GPL"
__version__ = "3.0"
__github__ = "github.com/OtenMoten"
__status__ = "Production"
__instagram__ = "instagram.com/kevin_ossenbrueck"
__facebook__ = "facebook.com/informatiker.kevin.ossenbrueck"

import talib.abstract as ta
from pandas import DataFrame
from typing import Dict, Any, Callable, List
from functools import reduce

from skopt.space import Categorical, Dimension, Integer, Real

import freqtrade.vendor.qtpylib.indicators as qtpylib
from freqtrade.optimize.hyperopt_interface import IHyperOpt

class_name = 'EMACrossOpt'

shortRangeBegin = 10
shortRangeEnd = 40
mediumRangeBegin = 50
mediumRangeEnd = 150

class EMACrossOpt(IHyperOpt):
    """
    Default hyperopt provided by freqtrade bot.
    You can override it with your own hyperopt
    """

    @staticmethod
    def populate_indicators(dataframe: DataFrame, metadata: dict) -> DataFrame:

        for short in range(shortRangeBegin, shortRangeEnd):
            dataframe['maShort(' + str(short) + ')'] = ta.EMA(dataframe, timeperiod=short)

        for medium in range(mediumRangeBegin, mediumRangeEnd):
            dataframe['maMedium(' + str(medium) + ')'] = ta.EMA(dataframe, timeperiod=medium)

        return dataframe

    @staticmethod
    def buy_strategy_generator(params: Dict[str, Any]) -> Callable:
        """
        Define the buy strategy parameters to be used by hyperopt
        """
        def populate_buy_trend(dataframe: DataFrame, metadata: dict) -> DataFrame:
            """
            Buy strategy Hyperopt will build and use
            """
            conditions = []

            # TRIGGERS
            if 'trigger' in params:
                for short in range(shortRangeBegin, shortRangeEnd):
                    for medium in range(mediumRangeBegin, mediumRangeEnd):
                        if params['trigger'] == "cross_short(" + str(short) + ')' + '_above_medium(' + str(medium) + ')':
                            conditions.append(qtpylib.crossed_above(dataframe['maShort(' + str(short) + ')'], dataframe['maMedium(' + str(medium) + ')']))

            if conditions:
                dataframe.loc[
                    reduce(lambda x, y: x & y, conditions),
                    'buy'] = 1

            return dataframe

        return populate_buy_trend

    @staticmethod
    def indicator_space() -> List[Dimension]:
        """
        Define your Hyperopt space for searching strategy parameters
        """
        buyTriggerList = []
        for short in range(shortRangeBegin, shortRangeEnd):
            for medium in range(mediumRangeBegin, mediumRangeEnd):
                buyTriggerList.append('cross_short(' + str(short) + ')_above_medium(' + str(medium) + ')')
        return [
            Categorical(buyTriggerList, name='trigger')
        ]

    @staticmethod
    def sell_strategy_generator(params: Dict[str, Any]) -> Callable:
        """
        Define the sell strategy parameters to be used by hyperopt
        """
        def populate_sell_trend(dataframe: DataFrame, metadata: dict) -> DataFrame:
            """
            Sell strategy Hyperopt will build and use
            """
            # print(params)
            conditions = []

            # TRIGGERS
            if 'sell-trigger' in params:
                for short in range(shortRangeBegin, shortRangeEnd):
                    for medium in range(mediumRangeBegin, mediumRangeEnd):
                        if params['sell-trigger'] == 'cross_medium(' + str(medium) + ')_above_short(' + str(short) + ')':
                            conditions.append(qtpylib.crossed_above(dataframe['maMedium(' + str(medium) + ')'], dataframe['maShort(' + str(short) + ')']))

            if conditions:
                dataframe.loc[
                    reduce(lambda x, y: x & y, conditions),
                    'sell'] = 1

            return dataframe

        return populate_sell_trend

    @staticmethod
    def sell_indicator_space() -> List[Dimension]:
        """
        Define your Hyperopt space for searching sell strategy parameters
        """
        sellTriggerList = []
        for short in range(shortRangeBegin, shortRangeEnd):
            for medium in range(mediumRangeBegin, mediumRangeEnd):
                sellTriggerList.append('cross_medium(' + str(medium) + ')_above_short(' + str(short) + ')')

        return [
            Categorical(sellTriggerList, name='sell-trigger')
        ]

    @staticmethod
    def generate_roi_table(params: Dict) -> Dict[int, float]:
        """
        Generate the ROI table that will be used by Hyperopt
        """
        roi_table = {}
        roi_table[0] = params['roi_p1'] + params['roi_p2'] + params['roi_p3']
        roi_table[params['roi_t3']] = params['roi_p1'] + params['roi_p2']
        roi_table[params['roi_t3'] + params['roi_t2']] = params['roi_p1']
        roi_table[params['roi_t3'] + params['roi_t2'] + params['roi_t1']] = 0

        return roi_table

    @staticmethod
    def stoploss_space() -> List[Dimension]:
        """
        Stoploss Value to search
        """
        return [
            Real(-0.5, -0.02, name='stoploss'),
        ]

    @staticmethod
    def roi_space() -> List[Dimension]:
        """
        Values to search for each ROI steps
        """
        return [
            Integer(10, 120, name='roi_t1'),
            Integer(10, 60, name='roi_t2'),
            Integer(10, 40, name='roi_t3'),
            Real(0.01, 0.04, name='roi_p1'),
            Real(0.01, 0.07, name='roi_p2'),
            Real(0.01, 0.20, name='roi_p3'),
        ]

    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Based on TA indicators. Should be a copy of from strategy
        must align to populate_indicators in this file
        Only used when --spaces does not include buy
        """
        dataframe.loc[
            (
                qtpylib.crossed_above(dataframe['maShort'], dataframe['maMedium'])
            ),
            'buy'] = 1

        return dataframe

    def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Based on TA indicators. Should be a copy of from strategy
        must align to populate_indicators in this file
        Only used when --spaces does not include sell
        """
        dataframe.loc[
            (
                qtpylib.crossed_above(dataframe['maMedium'], dataframe['maShort'])
            ),
            'sell'] = 1

        return dataframe
```

### CODE REVIEW

**Comment by xmatthias** [comment]
seems like a nice addition.

I think something with this PR is messed up though (i doubt that you'll want to merge master into new_strategy - both are within this repository, and don't include the hyperopt you mention above) ... 

you should rather:
* create a new branch in your fork of this repository
* commit this hyperopts file there in the approrpiate location
* make a PR from that new branch to this repositories `master` branch.

**Comment by OtenMoten** [comment]
Oh @xmatthias I don't really know how to work correctly with Github.

Do you have a manual?

**Comment by xmatthias** [comment]
well - [github help](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests) ... ?

**Comment by hroff-1902** [comment]
Closing it in favor of merged #58

**Pull request closed without merging**
