### PR TITLE
mabStra Strategy + Hyperopt

### PR DESCRIPTION
**Pull request by mablue**
mabStra is a simple moving averages division strategy + hyperopt file
You can change FTF, STF = 5, 10 to change FastMa and SlowMA timeframes(be carefull FTF will smaller number than STF)

Do hyperopt:
`freqtrade hyperopt --hyperopt mabStraHo --hyperopt-loss SharpeHyperOptLossDaily --spaces all --strategy mabStra --config config.json -e 1000`
```
+--------+-----------+----------+------------------+--------------+-----------------------------------+----------------+-------------+
|   Best |     Epoch |   Trades |    Win Draw Loss |   Avg profit |                            Profit |   Avg duration |   Objective |
|--------+-----------+----------+------------------+--------------+-----------------------------------+----------------+-------------|
| * Best |    1/1000 |     5446 |   1958   17 3471 |       -0.57% | -1,826.97391040 USDT (-3,097.35%) |        239.6 m |     6.80044 |
| * Best |    2/1000 |        1 |      0    0    1 |      -22.66% |  -11.34147638 USDT  (-22.66%) |        720.0 m |     3.02076 |                                      
| * Best |   20/1000 |      134 |     72   47   15 |        1.91% |  129.06851254 USDT  (256.07%) |      1,396.6 m |    -3.48951 |                                      
| * Best |   21/1000 |     1751 |   1023  588  140 |        2.72% | 2,896.41684894 USDT (4,762.25%) |      2,784.2 m |    -10.0418 |
|   Best |   40/1000 |     2698 |   1120 1443  135 |        1.77% | 2,980.94128514 USDT (4,766.55%) |      1,896.5 m |      -11.56 |                                    
|   Best |   54/1000 |     2049 |   1196  701  152 |        2.60% | 3,406.42233657 USDT (5,332.07%) |      2,531.3 m |    -11.9458 |                                    
|   Best |   67/1000 |      519 |    289  189   41 |        3.40% | 967.17764255 USDT (1,762.91%) |      1,939.0 m |    -13.4827 |                                      
|   Best |  168/1000 |     1255 |   1068  113   74 |        1.73% | 1,302.23528577 USDT (2,176.66%) |        537.2 m |    -14.9015 |                                    
|   Best |  413/1000 |     1368 |   1046  258   64 |        2.78% | 2,388.32492115 USDT (3,796.80%) |      1,011.8 m |    -14.9644 |                                    
```

I thested with this config:
```
.
.
.
    "max_open_trades": 100,
    "stake_currency": "USDT",
    "stake_amount": "unlimited",
    "tradable_balance_ratio": 1,
    "fiat_display_currency": "USD",
    "timeframe": "1h",
    "dry_run": true,
    "dry_run_wallet": 5000,
    "cancel_open_orders_on_exit": false,
    "unfilledtimeout": {
        "buy": 10,
        "sell": 30
    },
.
.
.
        "pair_whitelist": [
            ".*/USDT"
        ],
        "pair_blacklist": [
            ".*UP/USDT",
            ".*DOWN/USDT",
            ".*BULL/USDT",
            ".*BEAR/USDT",
            "PAX/USDT",
            "BUSD/USDT",
            "USDC/USDT",
            "TUSD/USDT"
        ]
.
.
.

```

### CODE REVIEW

**Review by xmatthias — APPROVED** [review]
LGTM :+1: 

Thanks for sharing!

**Comment by Metal-joker** [comment]
@mablue Nice work! Could you share your ask strategy and bid strategy config?

**Comment by mablue** [comment]
> @mablue Nice work! Could you share your ask strategy and bid strategy config?

Tnx. Its a default config.
I didnt changed anything but if you have Idea about that please say here

**Comment by jason1813** [comment]
What and where is mabStraHo? If I run the command I get:
` freqtrade - ERROR - Impossible to load Hyperopt 'mabStraHo'. This class does not exist or contains Python code errors.`

**Comment by mablue** [comment]
> What and where is mabStraHo? If I run the command I get:
> ` freqtrade - ERROR - Impossible to load Hyperopt 'mabStraHo'. This class does not exist or contains Python code errors.`

removed from repo. use this for now I will upgrade to one file format
https://github.com/freqtrade/freqtrade-strategies/blob/d7b36772b8dadd1cf2e9465a119ce401c71b3af3/user_data/hyperopts/mabStraHo.py

**Pull request merged**
